# Drop-in for systemd-nspawn@lani-services-test.service on a non-NixOS target host.
# Deploy to: /etc/systemd/system/systemd-nspawn@lani-services-test.service.d/override.conf
# Identical to lani-override.conf except the machine name.

[Unit]
RequiresMountsFor=/var/lib/lani-ci

[Service]
Environment=SYSTEMD_NSPAWN_UNIFIED_HIERARCHY=1
ExecStart=
ExecStart=systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --settings=override --machine=lani-services-test
